
[window]
dynamic_title = true
dynamic_padding = true
# decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 1

[font]
normal = { family = "Iosevka", style = "Regular" }
size = 14

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[terminal]
shell = "/opt/homebrew/bin/zellij"
